// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbQ55xpGfhu6meVljBqv3ZWzrd_ppSGX0',
    appId: '1:504772799902:web:8ee26bd2890acb22deba8f',
    messagingSenderId: '504772799902',
    projectId: 'chatbox-8fbe6',
    authDomain: 'chatbox-8fbe6.firebaseapp.com',
    storageBucket: 'chatbox-8fbe6.appspot.com',
    measurementId: 'G-SNNB9BGFZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyUKvQFdOlRoXuYyn33tFEyqn3hlcnK_A',
    appId: '1:504772799902:android:731dbbd1fd8773fcdeba8f',
    messagingSenderId: '504772799902',
    projectId: 'chatbox-8fbe6',
    storageBucket: 'chatbox-8fbe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHjES53GS41YRrEZw1-QBakdaXIghNoM',
    appId: '1:504772799902:ios:d6a679686ec1e8d7deba8f',
    messagingSenderId: '504772799902',
    projectId: 'chatbox-8fbe6',
    storageBucket: 'chatbox-8fbe6.appspot.com',
    iosBundleId: 'com.example.prashantChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHjES53GS41YRrEZw1-QBakdaXIghNoM',
    appId: '1:504772799902:ios:d6a679686ec1e8d7deba8f',
    messagingSenderId: '504772799902',
    projectId: 'chatbox-8fbe6',
    storageBucket: 'chatbox-8fbe6.appspot.com',
    iosBundleId: 'com.example.prashantChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbQ55xpGfhu6meVljBqv3ZWzrd_ppSGX0',
    appId: '1:504772799902:web:ba451f4e3edebcc4deba8f',
    messagingSenderId: '504772799902',
    projectId: 'chatbox-8fbe6',
    authDomain: 'chatbox-8fbe6.firebaseapp.com',
    storageBucket: 'chatbox-8fbe6.appspot.com',
    measurementId: 'G-HLV65TJ2NH',
  );
}
